/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package address.AddressManagement;

import entity.AddressManagement.District;
import entity.AddressManagement.Province;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author QuestionBoy
 */
public class AddDistrictGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddDistrictGUI
     */
    public AddDistrictGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressManagementPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AddressManagementPU").createEntityManager();
        districtText = new javax.swing.JTextField();
        searchDistrict = new javax.swing.JButton();
        back = new javax.swing.JButton();
        infoListView = new javax.swing.JScrollPane();
        infoList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        districtText.setText("tìm kiếm");
        districtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtTextActionPerformed(evt);
            }
        });

        searchDistrict.setText("Search");
        searchDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDistrictActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        infoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DefaultListModel model=new DefaultListModel();
        for(String item: AddProvinceGUI.alphaList){
            javax.persistence.Query query=AddressManagementPUEntityManager.createNamedQuery("District.findByProvinceidAndAlpha").setParameter("provinceid", AddAddressGUI.provinceid).setParameter("name", item+"%");
            java.util.List<District> result=query.getResultList();
            if(!result.isEmpty()) model.addElement(item);
            for(District a:result){
                model.addElement(a.getName());

            }
        }
        infoList=new JList(model);
        infoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoListMouseClicked(evt);
            }
        });
        infoListView.setViewportView(infoList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoListView)
                    .addComponent(districtText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchDistrict, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(districtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDistrict))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(infoListView, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void districtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtTextActionPerformed

    private void infoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoListMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >=2){
            //districtidGlobal=new String();
            String districtName=(String) infoList.getSelectedValue();
            javax.persistence.Query query=AddressManagementPUEntityManager.createNamedQuery("District.findByNameAndProvinceid").setParameter("name", districtName).setParameter("provinceid", AddAddressGUI.provinceid);
            java.util.List<District> districtList=query.getResultList();
            for(District district: districtList){
                AddAddressGUI.districtid=district.getDistrictid();
                AddAddressGUI.districtName=district.getName();
            }
            this.setVisible(false);
            AddAddressGUI new1=new AddAddressGUI();
            new1.district.setText(AddAddressGUI.districtName);new1.district.setForeground(Color.BLACK);
            new1.province.setText(AddAddressGUI.provinceName);new1.province.setForeground(Color.BLACK);
            new1.setVisible(true);
        }
    }//GEN-LAST:event_infoListMouseClicked

    private void searchDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDistrictActionPerformed
        // TODO add your handling code here:
        String districtName=districtText.getText();
        javax.persistence.Query query=AddressManagementPUEntityManager.createNamedQuery("District.findByHintAndProvinceid").setParameter("name", districtName+"%").setParameter("provinceid", AddAddressGUI.provinceid);

            java.util.List<District> result=query.getResultList();
            DefaultListModel model= new DefaultListModel();
            for(District a:result){
                model.addElement(a.getName());
            }
            infoList=new JList(model);
            infoListView.setViewportView(infoList);
    }//GEN-LAST:event_searchDistrictActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
        new AddDistrictGUI().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDistrictGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDistrictGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDistrictGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDistrictGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDistrictGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AddressManagementPUEntityManager;
    private javax.swing.JButton back;
    private javax.swing.JTextField districtText;
    private javax.swing.JList<String> infoList;
    private javax.swing.JScrollPane infoListView;
    private javax.swing.JButton searchDistrict;
    // End of variables declaration//GEN-END:variables
    private String districtGlobal;
    private String districtidGlobal;
}
