/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package address.AddressManagement;

import entity.AddressManagement.District;
import entity.AddressManagement.Ward;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JFrame;

/**
 *
 * @author QuestionBoy
 */
public class AddWardGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddWardGUI
     */
    public AddWardGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressManagementPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AddressManagementPU").createEntityManager();
        wardText = new CustomTextField(20);wardText.setPlaceholder("Tìm kiếm");
        searchWard = new javax.swing.JButton();
        back = new javax.swing.JButton();
        infoListView = new javax.swing.JScrollPane();
        infoList = new javax.swing.JList<>();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        wardText.setText("tìm kiếm");

        searchWard.setText("search");
        searchWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWardActionPerformed(evt);
            }
        });

        back.setText("Back");

        infoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DefaultListModel model=new DefaultListModel();
        for(String item: AddProvinceGUI.alphaList){
            javax.persistence.Query query=AddressManagementPUEntityManager.createNamedQuery("Ward.findByDistrictidAndAlpha").setParameter("districtid", AddAddressGUI.districtid).setParameter("name", item+"%");
            java.util.List<Ward> result=query.getResultList();
            if(!result.isEmpty()) model.addElement(item);
            //else System.out.println(AddAddressGUI.districtid);
            for(Ward a:result){
                model.addElement(a.getName());

            }
        }
        infoList=new JList(model);
        infoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoListMouseClicked(evt);
            }
        });
        infoListView.setViewportView(infoList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wardText, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(infoListView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(searchWard))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchWard))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(infoListView, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWardActionPerformed
        // TODO add your handling code here:
        String wardName=wardText.getText();
        javax.persistence.Query query=AddressManagementPUEntityManager.createNamedQuery("Ward.findByHintAndDistrictid").setParameter("name", wardName+"%").setParameter("districtid", AddAddressGUI.districtid);

            java.util.List<Ward> result=query.getResultList();
            DefaultListModel model= new DefaultListModel();
            for(Ward a:result){
                model.addElement(a.getName());
            }
            infoList=new JList(model);
            infoListView.setViewportView(infoList);
    }//GEN-LAST:event_searchWardActionPerformed

    private void infoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoListMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >=2){
            String wardName=(String) infoList.getSelectedValue();
            if(Arrays.asList(AddProvinceGUI.alphaList).contains(wardName)) return;

            javax.persistence.Query query=AddressManagementPUEntityManager.createNamedQuery("Ward.findByNameAndDistrict").setParameter("name", wardName).setParameter("districtid", AddAddressGUI.districtid);

            java.util.List<Ward> wardList=query.getResultList();
            for(Ward ward: wardList){
                AddAddressGUI.wardid=ward.getWardid();
                AddAddressGUI.wardName=ward.getName();
            }
            this.setVisible(false);
            AddAddressGUI new1=new AddAddressGUI();//System.out.println(AddAddressGUI.districtName);
            new1.district.setText(AddAddressGUI.districtName);new1.district.setForeground(Color.BLACK);
            new1.province.setText(AddAddressGUI.provinceName);new1.province.setForeground(Color.BLACK);
            new1.ward.setText(AddAddressGUI.wardName);new1.ward.setForeground(Color.BLACK);
            new1.setVisible(true);
        }
    }//GEN-LAST:event_infoListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AddressManagementPUEntityManager;
    private javax.swing.JButton back;
    private javax.swing.JList<String> infoList;
    private javax.swing.JScrollPane infoListView;
    private javax.swing.JButton searchWard;
    private CustomTextField wardText;
    // End of variables declaration//GEN-END:variables
    private String wardidGlobal;
    private String wardGlobal;
}
